apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-role-crossplane
data:
  roleName: {{ .Values.crossplane.vaultRole }}
  policyNames: {{ .Values.crossplane.vaultPolicyNames }}
  servieAccounts: "*"
  servieAccountNameSpaces: {{ .Values.crossplane.namespace }}
