apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-role-capten-agent
data:
  roleName: vault-role-capten-agent
  policyNames: {{ .Values.vault.policyNames | quote }}
  servieAccounts: {{ include "kad.serviceAccountName" . }}
  servieAccountNameSpaces: {{ .Release.Namespace }}