apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.vault.role | quote }}
data:
  roleName: {{ .Values.vault.role | quote }}
  policyNames: {{ .Values.vault.policyNames | quote }}
  servieAccounts: {{ include "server.serviceAccountName" . }}
  servieAccountNameSpaces: {{ .Release.Namespace }}