# On server start, the below apps config file will read and added to the store.
CreateStoreApps:
- falco
- loki
- signoz

# On server start, the below apps config will be read and updated in the store.
UpdateStoreApps:
- signoz
- loki
- signoz