name: Agent Docker Image CI

on:
  push:
    paths-ignore:
      - '**.md'
      - 'charts/**'
    branches:
      - 'main'
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - 'main'

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE: ${{ github.repository }}/agent
  GH_URL: https://github.com

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
            fetch-depth: 0
          
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - uses: docker/setup-buildx-action@v1
        name: Set up Docker Buildx

      -
        name: Login to ghcr registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            latest # Add the "latest" tag
   
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./dockerfiles/agent/Dockerfile
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE }}:${{ github.run_id }}
          labels: ${{ steps.meta.outputs.labels }}
         
          push: true
            
      - name: Install cosign
        uses: sigstore/cosign-installer@main

      - name: Sign the images
        run: |
          cosign sign -y ${{ env.REGISTRY }}/${{ env.IMAGE }}:${{ github.run_id }}
        env:
          COSIGN_EXPERIMENTAL: 1
      
      - name: Verify the pushed tags
        run: cosign verify ${{ env.REGISTRY }}/${{ env.IMAGE }}:${{ github.run_id }} --certificate-identity ${{ env.GH_URL }}/${{ github.repository }}/.github/workflows/agent-docker-image.yml@refs/heads/main  --certificate-oidc-issuer https://token.actions.githubusercontent.com
        env:
          COSIGN_EXPERIMENTAL: 1
      
      - name: Run Trivy in GitHub SBOM mode and submit results to Dependency Graph
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          format: 'github'
          output: 'dependency-results.sbom.json'
          image-ref: '.'
          github-pat: ${{ secrets.GITHUB_TOKEN }}
